// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7OTYAvdDN-c072YEsJNk06CdhTPcmzvw',
    appId: '1:430495517553:web:a8b9bed245724b1b5604d0',
    messagingSenderId: '430495517553',
    projectId: 'licentazinca',
    authDomain: 'licentazinca.firebaseapp.com',
    storageBucket: 'licentazinca.appspot.com',
    measurementId: 'G-53LVHX8PWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wjgImd2mO7VLu-veQWuEPdU9raDXAP4',
    appId: '1:430495517553:android:77d6d61837f55e205604d0',
    messagingSenderId: '430495517553',
    projectId: 'licentazinca',
    storageBucket: 'licentazinca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATo8j5GWwvE4E0qLl3pmk5qUyxBJp7GBY',
    appId: '1:430495517553:ios:8d3fbf90e55f692e5604d0',
    messagingSenderId: '430495517553',
    projectId: 'licentazinca',
    storageBucket: 'licentazinca.appspot.com',
    iosBundleId: 'com.example.cameraForTt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATo8j5GWwvE4E0qLl3pmk5qUyxBJp7GBY',
    appId: '1:430495517553:ios:9ca85fd32835c9415604d0',
    messagingSenderId: '430495517553',
    projectId: 'licentazinca',
    storageBucket: 'licentazinca.appspot.com',
    iosBundleId: 'com.example.camera.RunnerTests',
  );
}
